FROM golang:1.25 AS go-builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN apt-get update && apt-get install -y gcc ca-certificates
RUN CGO_ENABLED=1 go build -o main ./cmd/main.go

FROM debian:bookworm-slim AS production

WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=go-builder /app/main /app/main
COPY --from=go-builder /app/migrations /app/migrations
COPY .env .env

ENTRYPOINT ["/app/main"]